exec-once = waybar
exec-once = hyprpaper
exec-once = hyprsunset

$mainMod = SUPER
$animSpeed = 0.2
$terminal = kitty
$fileManager = kitty -e yazi
$menu = wofi --show drun -I

monitor=,preferred,auto,1

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen
bind = $mainMod, Space, exec, $menu
general {
    gaps_in = 4
    gaps_out = 6
    border_size = 1
	col.active_border = rgba(458588ff) rgba(282828ff) 45deg
    col.inactive_border = rgba(504945ff) rgba(282828ff) 45deg

}

decoration {
	rounding = 12
	inactive_opacity = 0.9
	blur {
		enabled = true
		size = 8
	}
}

input {
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =


    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    numlock_by_default = true

    touchpad {
        natural_scroll = true
		clickfinger_behavior = true
    }
}


# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Control tiling

# Move focus with SUPER + arrow keys
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d


# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

bindd = SUPER SHIFT, R, Reload config, exec, hyprctl reload

bind = SUPER CTRL, 1, movecurrentworkspacetomonitor, 0
bind = SUPER CTRL, 2, movecurrentworkspacetomonitor, 1

animations {
    enabled = yes
    # Windows
    animation = windows, 1, $animSpeed, default
    animation = windowsOut, $animSpeed, default
    animation = layers, 1, $animSpeed, default
    animation = layersOut, $animSpeed, default
    animation = border, $animSpeed, default
    animation = fade, $animSpeed, default

    # Disable workspace animation completely
    animation = workspaces, 0, 1, default
}

# Volume controls
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Microphone mute
bindel = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Brightness controls
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
