live_config_reload = true

# window stuff
window.opacity = 0.95
window.blur = true
window.title = "Terminal"

env.TERM = "xterm-256color"

# fonts
font.normal = {family = "MonaspiceAr Nerd Font", style="normal"}
font.bold = {family = "MonaspiceAr Nerd Font", style="bold"}
font.italic = {family = "MonaspiceAr Nerd Font", style="italic"}
font.bold_italic = {family = "MonaspiceAr Nerd Font", style="bold italic"}
font.size = 14


